models/topic.py
import time
import json
from models import Model
from models.user import User
from models.mongua import Mongua
import logging
import os
import time

ogger = logging.getLogger("bbs")


class Cache(object):
    def get(self, key):
        pass

    def set(self, key, value):
        pass


class MemoryCache(Cache):
    def __init__(self):
        self.cache = {}

    def get(self, key):
        return self.cache[key]

    def set(self, key, value):
        self.cache[key] = value


class RedisCache(Cache):
    import redis
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def set(self, key, value):
        return RedisCache.redis_db.set(key, value)

    def get(self, key):
        return RedisCache.redis_db.get(key)


class Topic(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('content', str, ''),
        ('title', str, -1),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('views', int, 0),
    ]

    should_update_all = True
    # 1. memory cache
    cache = MemoryCache()
    # 2. redis cahce
    redis_cache = RedisCache()

    def to_json(self):
        d = dict()
        for k in Topic.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self, key)
        return json.dumps(d)



    @classmethod
    def from_json(cls, j):
        d = json.loads(j)

        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        time.sleep(3)
        return Topic.all()

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def save(self):
        super(Topic, self).save()
        should_update_all = True

    @classmethod
    def cache_all(cls):

        # 2. redis cache
        if Topic.should_update_all:
            Topic.redis_cache.set('topic_all', json.dumps([i.to_json() for i in cls.all_delay()]))
            Topic.should_update_all = False
        j = json.loads(Topic.redis_cache.get('topic_all').decode('utf-8'))
        j = [Topic.from_json(i) for i in j]
        return j

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def reply(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms[-1]

    def replyuser(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        user = None
        if ms != []:
            recent_reply = ms[-1]
            recent_reply_userid = recent_reply.user_id
            user = User.find(id=recent_reply_userid)
        return user

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    if u is not None:
        log('DEBUG 回复 ->', form)
        m = Reply.new(form)
        m.set_user_id(u.id)
        return redirect(url_for('topic.detail', id=m.topic_id))
    return render_template('404.html')




routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board
from models.reply import Reply


main = Blueprint('topic', __name__)


import uuid
csrf_tokens = dict()
@main.route("/")
def index():
    # board_id = 2
    log('request ->', request)
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.cache_all()
        ms = Topic.all_delay()
    else:
        # ms = Topic.cache_find(board_id)
        ms = Topic.find_all(board_id=board_id)
    u = current_user()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, bs=bs, user=u)


@main.route('/<int:id>')
def detail(id):
    print(id)
    m = Topic.get(id)
    print(m)
    token = str(uuid.uuid4())
    u = current_user()
    if u is not None:
        csrf_tokens[token] = u.id
        log('csrf_tokens', csrf_tokens)
    else:
        csrf_tokens[token] = None
        log('csrf_tokens', csrf_tokens)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, token=token, user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    log('add form ->', form)
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    m = Topic.new(form, user_id=u.id)
    # for i in range(1000):
    #     m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    log('token ->', token)
    log('csrf_tokens ->', csrf_tokens)
    u = current_user()
    topic = Topic.get(id)
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == topic.user_id:
        csrf_tokens.pop(token)
        if u is not None:
            log('删除 topic 用户是', u, id)
            log('要删除的topic', Topic.get(id))
            topic = Topic.get(id)
            Topic.delete(topic)
            return redirect(url_for('topic.index'))
        else:
            return render_template('404.html')
    else:
        return render_template('403.html')


@main.route("/new")
def new():
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">
                <img class="navbarlogo" src="/static/image/navbarlogo.png">
            </a>
            {#     <form id="search_form" class="navbar-search" action="/search">#}
            {#      <input type="text" id="q" name="q" class="search-query span3" value="" />#}
            {#     </form>#}
            {% if user == None %}
                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    <li><a href="/signup">注册</a></li>
                    <li><a href="/signin">登录</a></li>
                </ul>
            {% else %}
                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>

                    <li>
                        <a href="/mail/">

                            未读消息
                        </a>
                    </li>

{#                    <li><a href="/profile">设置</a></li>#}
                    <li>
                        <a href="/logout" rel="nofollow">退出</a>
                    </li>

                    <li>
                        <a href="/profile" rel="nofollow">{{ user.username }}</a>
                    </li>

                </ul>
            {% endif %}
            <a class="btn btn-navbar" id="responsive-sidebar-trigger"> <span class="icon-bar"></span> <span
                    class="icon-bar"></span> <span class="icon-bar"></span> </a>
        </div>
    </div>
</div>

<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time }}
            </span>
                    <span>
                作者
                <a href="/user/hopperhuang">{{ topic.user().username }}</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 {{ topic.board().title }}
            </span>
                    <a class="topic_title" href="{{ url_for('topic.delete', id=topic.id, token=token) }}">
                        删除
                    </a>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ topic.content }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="/user/leiwei1991" class="user_avatar">
                        {% if r.user().user_image %}
                            <img src="{{ '/uploads/' + r.user().user_image + '?v=3&amp;s=120' }}"
                                 title="{{ r.user().username }}"/>
                        {% else %}
                            <img src="{{ url_for('static', filename='image/default.jpg') }}"
                                 title="{{ r.user().username }}"/>
                        {% endif %}
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ r.user().username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 • {{ r.created_time }}
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">
                        {{ r.content }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <br>
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<html>
<head></head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">
                <img class="navbarlogo" src="/static/image/navbarlogo.png">
            </a>
            {#     <form id="search_form" class="navbar-search" action="/search">#}
            {#      <input type="text" id="q" name="q" class="search-query span3" value="" />#}
            {#     </form>#}
            {% if user == None %}
                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    <li><a href="/signup">注册</a></li>
                    <li><a href="/signin">登录</a></li>
                </ul>
            {% else %}
                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>

                    <li>
                        <a href="/mail/">

                            未读消息
                        </a>
                    </li>

                    {#                    <li><a href="/profile">设置</a></li>#}
                    <li>
                        <a href="/logout" rel="nofollow">退出</a>
                    </li>

                    <li>
                        <a href="/profile" rel="nofollow">{{ user.username }}</a>
                    </li>

                </ul>
            {% endif %}
            <a class="btn btn-navbar" id="responsive-sidebar-trigger"> <span class="icon-bar"></span> <span
                    class="icon-bar"></span> <span class="icon-bar"></span> </a>
        </div>
    </div>
</div>
</body>
</html>
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">群口相声</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部
                </a>

                {% for b in bs %}
                    <a href="/topic?board_id={{ b.id }}"
                       class="topic-tab current-tab">
                        {{ b.title }}
                    </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                        <div class="cell">
                            {% if t.user() %}
                                <div class="topic_title_wrapper">

                                    <a class="user_avatar pull-left">
                                        {% if t.user().user_image %}
                                            <img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}title="atian25"/>
                                        {% else %}
                                            <img src='{{ url_for('static', filename='image/default.jpg') }}'>
                                        {% endif %}
                                    </a>

                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                    <span class="topiclist-tab">{{ t.board().title }}</span>
                                    <span>{{ t.replies() | count }}评论 / {{ t.views }}次浏览</span>
                                    {#                                <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">#}
                                    {#                                    删除#}
                                    {#                                </a>#}
                                    <a class="last_time pull-right">
                                        {% if t.replyuser() and t.reply() %}
                                            <span class="last_active_time">最近评论 {{ t.replyuser().username }}</span>
                                            <span class="last_active_time">{{ t.reply().created_time }}</span>
                                        {% endif %}

                                    </a>

                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="pagination" current_page="1">
                    <ul>


                        <li class="disabled"><a>«</a></li>


                        <li class="disabled active"><a>1</a></li>


                        <li><a href="/?tab=all&amp;page=2">2</a></li>


                        <li><a href="/?tab=all&amp;page=3">3</a></li>


                        <li><a href="/?tab=all&amp;page=4">4</a></li>


                        <li><a href="/?tab=all&amp;page=5">5</a></li>


                        <li><a>...</a></li>


                        <li><a href="/?tab=all&amp;page=101">»</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function () {
        var editor = new Editor();
        editor.render($('.editor')[0]);
    })();

</script>
</body>
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            <option value="">请选择</option>
                {% for b in bs %}
                <option value="{{ b.id }}">{{ b.title }}</option>
                {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>